### ISSUE TITLE
Change "whitelisted" relier configuration flag to "trusted", so that it's more meaningful and less biased

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-oauth-server#188]
These things matter:

http://www.cs.virginia.edu/~evans/cs655/readings/purity.html

**Comment by rfk** [comment]
We're at the stage where we have to deal with third-party reliers, so let's bite the bullet and move this issue forward.  @seanmonstar points out that non-whitelisted clients are currently not supported *at all* and will actually error out:

  https://github.com/mozilla/fxa-oauth-server/blob/master/lib/routes/authorization.js#L148

To minimise churn, and because I can't come up with anything compellingly better, I propose we do `s/whitelisted/trusted/g` throughout, which is at least a little more suggestive of what this property is meant to distinguish.

We can then use trustedness of the client to restrict scopes as described in #243.
