### ISSUE TITLE
EADDRINUSE error exists with status code 0.

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#244]
![image](https://cloud.githubusercontent.com/assets/128755/7357055/403d1d9c-ecfa-11e4-9388-3877669090b0.png)

This causes issues with fxa-local-dev

**Comment by vladikoff** [comment]
` node bin/internal.js` is also affected

**Comment by rfk** [comment]
@chilts this may be a simple place to dive in and start for more familiarity with oauth server operation

**Comment by chilts** [comment]
Alrighty ... this one was driving me up the wall, and here's why.

The `server.start(...)` callback in `bin/server.js` doesn't ever get called when Hapi gets a `EADDRINUSE`. It seems that Hapi's `pack.start()` does some initialisation which means it's doing something async, the main program is running down to the bottom but when Hapi then tries to listen it throws an error which the promise can't wrap since it's on a subsequent tick. i.e. https://github.com/mozilla/fxa-oauth-server/blob/master/bin/server.js#L12-L19.

Also we can't put a `.catch()` or `.finally()` or `.done()` or whatever it is at line 19 here since if we (change it slightly and choose to) return a deferred promise from the above function, it'll never resolve/reject since that callback since is never called due to the throw above.

This part is interesting. None of the above stuff works (and many other things I've tried) but mozlog/intel knows about the exception and logs it, presumably a `process.on('uncaughtException', fn)` so I did the same and put one of those in at the bottom of the file (see below) and yes we can at least see the exception. Essentially adding this at the bottom of `bin/server.js` means we can make the process return non-zero:

```
process.on('uncaughtException', function(err) {
  process.exit(2)
});
```

Success? No, it's not that "simple" (air-quotes)!

Strangely, without that mozlog/intel is the only thing listening to `uncaughtException` and because all it does is output the error I think node then says "well, you listened for it and dealt with it, so I'll just quit with a zero exit code". Hmm. Testing this myself by just doing a `console.log('Blah!')` instead of `process.exit(2)` shows that we output 'Blah!' and the exit code is zero! So yeah ...

Ah ok, saw this : https://github.com/seanmonstar/intel/blob/ad9b25ccd3968aa39b649c0dabe695dd056a137d/README.md#logging-exceptions

Does this mean that intel is exiting, but exiting with zero status?

The fix is ... listening to `uncaughtException` and doing a `process.exit(2)`. Wow, this is not nice ... any other recommendations? @seanmonstar Would this be a bug in one of mozlog/intel, a config error somewhere or not at all? Not sure if I've understood all that correctly so am hoping for confirmation from you. :wink: @rfk you sent me on a wild goose chase with this one :tongue: - so, what are your thoughts? :joy:

And since my brain has now melted and it's almost my weekend, I'm going to watch a YouTube video for a GoLang tutorial!

![homer-brain](https://cloud.githubusercontent.com/assets/3048/7646506/9ca1168e-fb18-11e4-8128-1d37bfa123eb.gif)

**Comment by seanmonstar** [comment]
If intel is able to trigger the exit, it should exit with code `1`: https://github.com/seanmonstar/intel/blob/master/lib/logger.js#L201

**Comment by rfk** [comment]
> @rfk you sent me on a wild goose chase with this one 

Yes, I'm very helpful like this :-)

ISTM the right thing here is to get mozlog/intel/whatever to do the right thing w.r.t. exiting, which may be just a config issue on our side.

**Comment by vladikoff** [comment]
:eyes:

**Comment by seanmonstar** [comment]
I tried this:

```js
process.on('exit', function(code) { console.log(code); });
process.on('uncaughtException', function() {
  process.exit(5);
});
```

And then running `node bin/server.js` twice, resulted in the second logging `100`, and `echo $?` also shows me 100.

**Comment by chilts** [comment]
@seanmonstar yes, that function in `lib/logger.js` is called, but the program exits (with zero code) prior to the timeout being called back since the `t` is `t.unref()`.

Anyway, am just gonna stick to what I originally suggested above, which is similar to your 2nd comment (without the `.on('exit', ...)`), just the `.on('uncaughtException', ...)`.

**Comment by seanmonstar** [comment]
It's been a while, but I think I put the timeout so the process could clean
up. If I exited immediately, stdout wouldn't always flush the final log
message out. Blah blah, stupid dumb.
