### ISSUE TITLE
Track last-used-at time for refresh tokens

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-oauth-server#275]
This will be usedful metadata to include in a future management dashboard.

**Comment by vladikoff** [comment]
> future management dashboard.

👀  Do you think this will still be beneficial for the OAuth dashboard?

**Comment by rfk** [comment]
Yes I do, however I don't think it needs to be a high priority for now

**Comment by vladikoff** [comment]
From notes:

* One of the task is to create a new database migration .sql file and alter the `refreshTokens` table and introduce a new column (`lastUsedAt`?). https://github.com/mozilla/fxa-oauth-server/blob/master/lib/db/mysql/patches/patch-005-006.sql#L3-L17

* Task: Find a way to set `lastUsedAt` to `createdAt` on token create.

* Task: Find a way to keep `lastUsedAt` updated. Probably a DB update every time the token is queried. (But not too often to avoid DB overload. Probably if token was used within last day, then do not update `lastUsedAt`)


@rfk anything else you wanna see for this?

**Comment by rfk** [comment]
> Probably a DB update every time the token is queried.

This is probably the best place to start.  Every use of a refresh token will already produce a DB write operation, since it generates a new access token.  So hopefully we won't run into too many issues with the write load here.

> anything else you wanna see for this?

Nope, sounds good to me!

**Comment by seanmonstar** [comment]
A possible alternative is to never delete the most recent access token. We
can mark it as expires in the code base, but that way we already have a
record of 'last used', pretty much for free!

**Comment by rfk** [comment]
Interesting idea; I wonder how much this would complicate the access-token-purging script.

**Comment by vladikoff** [comment]
> never delete the most recent access token

Not sure I like the sound of that or maybe I just don't understand the trick here.
Let me know if you really want to go with that or just make a proper `lastUsed` column.

**Comment by vbudhram** [comment]
> how much this would complicate the access-token-purging script.

Normally, all expired tokens would get deleted by the purge token script. Marking token expired (if it was really wasn't expired?) could add complexity to the script to find out if it really has expired. Is it possible for a user to have multiple active, not expired tokens? I might be missing something too.

**Comment by seanmonstar** [comment]
> never delete the most recent access token

We already have code to detect when an access token is expired: https://github.com/mozilla/fxa-oauth-server/blob/master/lib/token.js#L19-L27

The expired token error is commented out, since we wanted to wait till people switch to refresh token (I hope they have by now?). There's no risk of the token being used past its expiration (once we start rejecting them). Purging them is simply a useful maintenance to stop storing tokens that are no longer useful. Especially useful since with refresh tokens, the expected usage is that a service receives an access token each time they wish to query for data, so there would possibly be many old access tokens.

> how much this would complicate the access-token-purging script.

It'd likely require turning the script into a query-then-delete, instead of just `DELETE FROM tokens WHERE expiredAt < now()`.

**Comment by rfk** [comment]
It's possible for access-tokens to be explicitly destroyed, rather than just waiting for them to expire, which would remove the record of activity.  So on reflection, I lean towards keeping it simple and just storing the timestamp explicitly.

**Comment by seanmonstar** [comment]
Oh good point, I forgot about destroying tokens.
