### ISSUE TITLE
Receive 'Invalid request signature' when 'scope=profile' in sign in URL

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/fxa-oauth-server#314]
Hi,

I'm trying to initiate a sign in using Firefox Accounts with the scope parameter set to 'profile'.  The example docs show that you can set it to 'profile' or more specifically 'profile:email'.  I would like the entire profile, however if I set my scope=profile in my sign in URL I receive 'Invalid request signature'.

An example of a working login is here:

https://stable.dev.lcip.org/signin?client_id=b9884421b4a4507f&state=none&scope=profile%3Aemail

However if I set it to:

https://stable.dev.lcip.org/signin?client_id=b9884421b4a4507f&state=none&scope=profile

I see 'Invalid request signature'.  

Is this an expected behaviour, and if so, how do I specify that I want access to the entire profile?

Thanks!

**Comment by rfk** [comment]
Hi @jaredkerim.  Looks like the website is reporting the wrong error message to you here, because of some weirdness with how our error numbers numbers overlap on fxa-auth-server and fxa-oauth-server.  You're getting `errno=109` which is "invalid request signature" on the auth server, but "invalid request parameter" here on the oauth-server.  Sounds like a bug in the frontend content that it's showing you the error message from the wrong context.

(The reasons for this overlap are historical and I hope to clean them up moving forward)

Looking at the network response, it looks like  Joi validation error on the `scope` parameter, but it's not obvious to me why that'd be failing.

@jaredkerim I see your client_id is not marked as "trusted", which means you're only allowed to request certain scopes.  "profile:email" is allowed for untruated reliers, but not the full "profile" scope (yet).  That's *probably* why this is failing, but it's failing with the wrong errno.

If you created this client_id yourself on https://oauth-stable.dev.lcip.org/console/, try creating one that's marked as trusted and see if this helps.

**Comment by shane-tomlinson** [comment]
errno 109 is labeled as [INVALID_REQUEST_SIGNATURE](https://github.com/mozilla/fxa-content-server/blob/9ec6b1812e76fa9576462bd9c4cebf4544698f9f/app/scripts/lib/oauth-errors.js#L50) in the oauth server errors list. 

It looks like both 108 and 109 are incorrect on the front end:

```js
    INVALID_PARAMETER: {
      errno: 108,
      message: t('Invalid parameter in request body: %(param)s')
    },
    INVALID_REQUEST_SIGNATURE: {
      errno: 109,
      message: t('Invalid request signature')
    },
```

These have been in the front end for over a year, I'm surprised we have not caught this earlier. Filed https://github.com/mozilla/fxa-content-server/issues/2830.

**Comment by shane-tomlinson** [comment]
Closing this issue here, this is a content server problem.

**Comment by shane-tomlinson** [comment]
Re-opening to investigate the joi problem @rfk mentions in:

> Looking at the network response, it looks like Joi validation error on the scope parameter, but it's not obvious to me why that'd be failing.

**Comment by shane-tomlinson** [comment]
@rfk -  The front end [filters out disallowed scopes](https://github.com/mozilla/fxa-content-server/blob/9ec6b1812e76fa9576462bd9c4cebf4544698f9f/app/scripts/models/reliers/oauth.js#L202) for untrusted reliers, causing the `scope` field to be an empty string `""` in the request to `https://oauth-stable.dev.lcip.org/v1/authorization`.

```json
{
 "assertion":...,
 "client_id":"b9884421b4a4507f",
 "scope":"",
 "state":"none"
}
```

Since `scope` is [not marked as optional](https://github.com/mozilla/fxa-oauth-server/blob/5a45f5a1caa72f640d728bc60827b2e6a2049f4b/lib/routes/authorization.js#L110-L111), my guess is Joi throws the exception.

**Comment by rfk** [comment]
Nice catch, that'd definitely explain it.  I think the server's behaviour in that case is correct then, and we'll have to depend on the client to throw an error in this situation.
