### ISSUE TITLE
Create Oauth client for IAM

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-oauth-server#515]
For IAM to test integration with Firefox Accounts, they will need their own Oauth client. However, I am unsure of what the client properties should be

Ex.

```
    {
      "id": "dcdb5ae7add825d2",
      "hashedSecret": "289a885946ee316844d9ffd0d725ee714901548a1e6507f1a40fb3c2ae0c99f1",
      "name": "Firefox Accounts IAM",
      "imageUri": "{{ oauth_public_url }}/img/logo@2x.png",
      "redirectUri": "{{ rp_public_url }}/api/oauth",
      "trusted": true,
      "canGrant": false
    }
```

**Comment by gdestuynder** [comment]
Hi,
Currently Mozilla IAM is hooked up to stage for testing (i.e. limited to `redirect_uri=http://localhost`) which seems to work ok.
I have some code that converts whatever structured data back to our profile data for integration.

Mainly, it *seems* like Fxa Prod supports openid (at least partially) which is standard and I can easily use. I couldn't use it on stage (it refuses the `openid` scope), so I did only the oauth2 authentication and profile retrieval (scope `profile:email`).

Our redirect uris are:

- https://auth-dev.mozilla.auth0.com/login
- https://auth.mozilla.auth0.com/login

Currently I'm using `https://oauth-stable.dev.lcip.org/v1/authorization` for getting the code (i.e. am using code flow) and `https://oauth-stable.dev.lcip.org/v1/token` for getting the access_token back, then `https://oauth-stable.dev.lcip.org/v1/profile` for getting the user's email.

On our side the user profile [looks like this currently](https://github.com/mozilla-iam/cis/blob/master/tests/data/profile-good.json) (see also [docs](https://github.com/mozilla-iam/cis/blob/master/docs/Profiles.md))

I'm thinking about matching the email from the profile claims (or the claim `sub` if openid works) to `userName`, `primaryEmail`, and construct `user_id` (which is the equivalent of `sub` for us ie the uuid for the user) as such: `fxa|<some_uuid_here>`.

Hopefully this helps setup anything that needs to be setup on your side.

**Comment by rfk** [comment]
> Currently Mozilla IAM is hooked up to stage for testing

IIUC, you're currently using our "stable dev" environment with client id [1a118eae25503e99](https://oauth-stable.dev.lcip.org/v1/client/1a118eae25503e99).

This client id is currently marked `trusted: false`, which restricts the scopes that it can request.  I'm going to update it to `trusted: true` since I assume that's what we'll be running with in production.

> I couldn't use it on stage (it refuses the openid scope), so I did only the oauth2
> authentication and profile retrieval (scope profile:email)

The `trusted: false` flag currently limits you to requesting only very specific profile sub-scopes such as profile:email, which is probably why the openid scope isn't working.  @gdestuynder can you please try using openid again now that I've updated you to `trusted: true`?

> I'm thinking about matching the email from the profile claims (or the claim sub if openid works)
> to userName, primaryEmail, and construct user_id (which is the equivalent of sub for us ie the uuid
> for the user) as such: fxa|<some_uuid_here>.

I have some vague recollection that "<sub>@<iss>" is preferred for OIDC reliers, which would make the user_id "<uid>@accounts.firefox.com" in this case.  I don't see any harm from constructing it another way like you suggest above, however.

(I'm pretty sure we provide the uid as `sub` claim rather than the email address, since it's the only stable identifier for the account).

**Comment by gdestuynder** [comment]
@rfk thanks `openid` (and `openid profile`) scopes now work with the current client id.

The user_id construction maps the auth0 internal `user_id` for us basically, I'm happy to get `<sub>@<iss>` though. Note, most RPs we use (wrongly) ignore the `user_id` and use the primary email instead. Due to this, we attempt to ensure the primary email field is just as stable as the `user_id`. 
In reality for us the LDAP primary email is stable, the google email is stable, the github email is not stable (even though its used as if it was by many rps)

**Comment by rfk** [comment]
> Due to this, we attempt to ensure the primary email field is just as stable as the user_id.

Just to be clear: we can't realistically ensure this for FxA.  I'm not sure there's much we can do about RPs assuming it is, though...

**Comment by gdestuynder** [comment]
I suspect it'll be like GitHub for us - where we do a best effort to ensure it's consistent, but at the end of the day it's in the hands of the RP to handle email transitions correctly when used as identifier for the account.

**Comment by rfk** [comment]
Yeah.  We already went through this with Pocket, who were treating the email from FxA as a unique identifier and had to do some migration work when we shipped the ability to change your FxA email.  "Best Effort" is really the best we can do in these cases.

**Comment by vladikoff** [comment]
from mtg: 

Need to add client to:

* fxa-dev (need a PR)
* stage (bugzilla bug)
* prod (bugzilla bug)

**Comment by vladikoff** [comment]
@rfk to close bugzilla bug 👍

**Comment by rfk** [comment]
Dev PR:

  https://github.com/mozilla/fxa-dev/pull/349

Bugzilla bug:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1436249

**Comment by rfk** [comment]
@gdestuynder could you please check on the details in the above two bugs?

**Comment by vladikoff** [comment]
Done! Thanks @jrgm !
