### ISSUE TITLE
Figure out support for `+` in scope separation

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-oauth-server#552]
This could be a content server thing, but the servo/rust-url thing generates `profile+openid` URLs from a given `profile openid` string. Then the oauth flow gets stuck somewhere in the process. Ref https://github.com/servo/rust-url/blob/de977b52731c2c3a5de16aa73cd5656812041b25/src/form_urlencoded.rs#L364-L367

**Comment by rfk** [comment]
> This could be a content server thing

Especially when we end up deprecating the initial OAuth redirect from here, and direct clients straight to content-server:

  https://github.com/mozilla/fxa-content-server/issues/6113

Assuming we go ahead with that plan, I think oauth-server should never need to know about `+` vs ` ` in scope strings - the encoding should always be handled by content-server and oauth-server would only ever see space-separated scope strings (with no `+` symbols because we don't use `+` in any of our supported scopes).

**Comment by shane-tomlinson** [comment]
@vladikoff and @rfk - can you triage this?

**Comment by vladikoff** [comment]
Next

**Comment by vladikoff** [comment]
Vlad to check if this is a front-end issue...

**Comment by vladikoff** [comment]
This is fine now, we removed the workaround in https://github.com/mozilla/application-services/commit/ace4daed0d0744d984ec90930411670a1ed4e915

**Comment by vladikoff** [comment]
this don't work 

```
https://accounts.firefox.com/authorization?client_id=98adfa37698f255b&redirect_uri=https%3A%2F%2Flockbox.firefox.com%2Ffxa%2Fios-redirect.html&scope=profile+https%3A%2F%2Fidentity.mozilla.com%2Fapps%2Foldsync+https%3A%2F%2Fidentity.mozilla.com%2Fapps%2Flockbox&response_type=code&state=hnRQWHAGWB-3cJaFpzy0IA&code_challenge_method=S256&code_challenge=hnMS0-7hXumSfC9e3mtB2o2zBQ6xtxg4uTeXOyb9n1Y&access_type=offline&keys_jwk=eyJjcnYiOiJQLTI1NiIsImt0eSI6IkVDIiwieCI6IldXZ1lDb2ZYZkphWjhhbUkyWFBudzNXU2J2M0JXYWRFdVJkRWFJa2lyMk0iLCJ5IjoiMTM3OXFHUU9HN1ZpTzN1MXNfSVIxZHJ0MW1HNUdoZ3Z4M2pYaUF6cFFabyJ9
```

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-content-server/commit/f57c087568764d58049dc378030b336a3fd94ae9
