### ISSUE TITLE
CORS broken when x-requested-with included

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-oauth-server#560]
When the browser includes a `Access-Control-Request-Headers: x-requested-with` header (which they all seem to do now) with the `OPTIONS` request the server replies with `{"message":"CORS error: Some headers are not allowed"}`.

See https://123done-stable.dev.lcip.org using "Sign in with PKCE" for example.

**Comment by vladikoff** [comment]
I think the example is broken there, after this commit: https://github.com/mozilla/123done/commit/d1b7f9f6d603a3702fea61861e14c2df6c519627#diff-f958f853ed0f30cf43a515a2f89991f3R93

we started redirecting the `/api/login` route and instead of returning some json info, it in now redirects the XHR request to the OAuth / Content Server. That is a bad example, do not follow that.
